---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "hurlenko/filebrowser"
    pull: yes
    labels:
      "flame.type": "application"
      "flame.name": "{{ container_name | title }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    state: 'started'
    user: "1000:1000"
    env:
      FB_BASEURL: /filebrowser
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/{{ container_name }}/data/config:/config"
      - "{{ storage_drive }}:/data/stuff"
    restart_policy: unless-stopped
    ports:
      - 3789:8080
    networks:
      - name: '{{ reverse_proxy_net }}'

