---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/sonarr"
    pull: yes
    labels:
      "flame.type": "application"
      "flame.name": "{{ container_name | title }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
      "traefik.enable":	"true"
      "traefik.http.routers.sonarr.rule":	"Host(`{{ nginx_server_name }}`)"
      # "traefik.http.services.sonarr.loadbalancer.server.port": "8096"
    state: 'started'
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ storage_drive }}/series:/tv"
      - "{{ storage_drive }}/downloads:/downloads"
    restart_policy: unless-stopped
    ports:
      - 8989:8989
    networks:
      - name: '{{ reverse_proxy_net }}'

# - name: Add {{ container_name }} to the SWAG network (reverse-proxy)
#   docker_network:
#     name: swag_internal_network
#     connected:
#       - "{{ container_name }}"
#     appends: yes
#   when: enable_swag

- name: "Set {{ container_name }} nginx configuration"
  include_tasks: "{{ playbook_dir }}/tasks/nginx_vhost.yml"
  when: enable_nginx | default(False)
