---
- name: Make sure the {{ container_name }} data folder is created
  file:
    dest: "{{ docker_dir }}/{{ container_name }}/data"
    state: directory
    owner: "{{ username }}"
    group: "docker"
    mode: "0777"
    recurse: yes

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "grafana/grafana-oss:latest"
    pull: yes
    labels:
      "flame.type": "application"
      "flame.name": "{{ container_name | title }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    state: 'started'
    user: "1000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/{{ container_name }}/data:/var/lib/grafana"
    restart_policy: unless-stopped
    ports:
      - 9300:3000
    networks:
      - name: 'prometheus_default'
      - name: '{{ nginx_npm_docker_net }}'

# - name: Add {{ container_name }} to the SWAG network (reverse-proxy)
#   docker_network:
#     name: swag_internal_network
#     connected:
#       - "{{ container_name }}"
#     appends: yes
#   when: enable_swag

- name: "Set {{ container_name }} nginx configuration"
  include_tasks: "{{ playbook_dir }}/tasks/nginx_vhost.yml"
  when: enable_nginx | default(False)
