#
# Packages
#
extra_packages:
  - speedtest-cli
  - htop
  - git
  - neofetch
  - neovim
  - tmux
  - rsync
  - lm-sensors
  - iotop
  - iftop
  - ncdu
  - hddtemp
  - reptyr
  - vnstat
  - iptables-persistent

#
# Docker-compose url
#
docker_compose_url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"

#
# Apt mirrors
#
# version: focal

# apt_mirror: http://ftp.uni-mainz.de/ubuntu/


#
# Email credentials (for SMART and Snapraid error reporting)
#

email: "{{ vault_email }}"

email_login: "{{ vault_email }}"

email_smtp_host: "{{ vault_email_smtp_host }}"

email_smtp_port: "{{ vault_email_smtp_port }}"

email_smtp_port_ssl: "{{ vault_email_smtp_port_ssl }}"

#
# Enable/disable functionality
#
enable_nas_stuff: true

enable_samba: false

enable_portainer: true

# Home automation

enable_homeassistant: false

# Projects

enable_kanboard: false

enable_wekan: false

enable_gitea: false

# Media

enable_jellyfin: true

enable_photoprism: false

# Yo-ho-ho

enable_deluge: true

enable_sonarr: true

enable_radarr: false

enable_openbooks: false

enable_jackett: false

# Public-facing services

enable_nextcloud: false

# DDNS

enable_ddclient: false

# VPN

enable_wireguard: false

# network bridge

enable_net_bridge: false

# Homepages

enable_homer: true

# Misc

enable_authelia: false

enable_pihole: false

enable_watchtower: false

enable_endlessh: false

enable_registry: false

enable_minidlna: false
  
enable_virtualization: false

#
# Web Server
#

enable_nginx: false

enable_nginx_npm: false

nginx_npm_docker_net: reverse_proxy_net

#
# System monitoring
#

enable_grafana: false

enable_prometheus: false

#
# Time Machine
#
timemachine_root: /mnt/timemachine

timemachine_drive: /dev/disk/by-label/TimeMachine

enable_timemachine: false

samba_server_string: "{{ hostname }}"

samba_log: "/var/log/samba.log"

samba_users:
  - name: "{{ username }}"
    password: "{{ password }}"
#   - name: "{{ additional_users[0].name }}"
#     password: "{{ password2 }}"

# samba_global_include: global-include.conf

# samba_apple_extensions: yes

samba_mitigate_cve_2017_7494: false

samba_load_homes: yes

samba_log_level: '3 passdb:5 auth:10 winbind:2 '

# samba_server_max_protocol: "SMB3"

# samba_server_min_protocol: "SMB2"

# samba_shares:
#   - name: Trash
#     guest_ok: no
#     public: no
#     read_only: no
#     writable: yes
#     owner: "{{ username }}"
#     browseable: yes
#     path: "{{ mergerfs_root }}"
#     valid_users: "{{ username }}"
#     write_list: "{{ username }}"

  # - name: Downloads
  #   guest_ok: no
  #   public: no
  #   read_only: no
  #   writable: yes
  #   browseable: yes
  #   owner: "{{ username }}"
  #   path: "{{ storage_drive }}/downloads"
  #   valid_users: "{{ username }}"
  #   write_list: "{{ username }}"

#
# MergerFS
#
# mergerfs_root: /mnt/coisas

# cache_root: /mnt/storage_cache

# enable_mergerfs: false

# disks:
#   - { path: /mnt/data1, src: /dev/disk/by-label/Data1, content: true }
#   - { path: /mnt/data2, src: /dev/disk/by-label/Data2, content: true }
#   - { path: /mnt/data3, src: /dev/disk/by-label/Data3, content: true }

# cache_disks:
#   - { path: /mnt/cache1, src: /dev/disk/by-label/Cache1, content: true }
#   - { path: /mnt/cache2, src: /dev/disk/by-label/Cache2, content: true }

# parity_disks:
#   - { path: /mnt/parity1, src: /dev/disk/by-label/Parity1, content: true }

#
# Backups Folder
#
backups_folder: /mnt/backups

#
# Storage Drive
#
storage_drive: /mnt/stuff

#
# Security
#
enable_crowdsec: false

enable_iptables: true

enable_fail2ban: false

# We have our own f2b rules
security_fail2ban_enabled: false

### BEGIN Secret variables (encrypt and put into vault.yml)
email_password: '{{ vault_email_password }} '
host: ''
host_local: '{{ vault_host_local }}'
password: "{{ vault_user_password }}"
photoprism_password: ''
pihole_password: ''
pikvm_password: ''
ssh_public_key: ''
vpn_host: ''
vpn_password: ''
### END Secret variables (encrypt and put into vault.yml)l
