---
- name: Create {{ container_name }} network.
  docker_network:
    name: '{{ container_name }}_net'

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "gitea/gitea:1.16.0"
    pull: yes
    labels:
      "flame.type": "application"
      "flame.name": "{{ container_name | title }}"
      "flame.url": "{{ dashboard_url }}"
      "flame.icon": "custom"
    state: 'started'
    env:
      "USER_UID": "{{ guid }}"
      "USER_GID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ docker_dir }}/{{ container_name }}/volume:/data"
    restart_policy: unless-stopped
    ports:
      - 8300:3000
      - '8222:22'
    networks:
      - name: "{{ container_name }}_net"
      - name: '{{ nginx_npm_docker_net }}'

# - name: Add {{ container_name }} to the SWAG network (reverse-proxy)
#   docker_network:
#     name: swag_internal_network
#     connected:
#       - "{{ container_name }}"
#     appends: yes
#   when: enable_swag

- name: "Set {{ container_name }} nginx configuration"
  include_tasks: "{{ playbook_dir }}/tasks/nginx_vhost.yml"
  when: enable_nginx | default(False)
