---
- name: Install the {{ container_name }} docker-compose file
  copy:
    src: "files/docker-compose.yml"
    dest: "{{ docker_dir }}/{{ container_name }}/docker-compose.yml"
    mode: 0664
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_stack:
    state: present
    name: wekan
    compose:
      - "{{ docker_dir }}/{{ container_name }}/docker-compose.yml"
      - version: '3'
        services:
          wekandb:
            volumes:
              - "{{ docker_dir }}/{{ container_name }}/wekan-db:/data/db"
              - "{{ docker_dir }}/{{ container_name }}/wekan-db-dump:/dump"
              - "{{ docker_dir }}/{{ container_name }}/wekan-db-config:/data/configdb"

- name: "Set {{ container_name }} nginx configuration"
  include_tasks: "{{ playbook_dir }}/tasks/nginx_vhost.yml"
  when: enable_nginx | default(False)
