---

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "portainer/portainer-ce:2.11.0"
    pull: true
    state: 'started'
    labels:
      "traefik.enable":	"true"
      "traefik.http.routers.portainer.rule":	"Host(`{{ nginx_server_name }}`)"
      "traefik.http.services.portainer.loadbalancer.server.port": "9000"
    env:
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/portainer_data:/data"
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    restart_policy: unless-stopped
    networks:
      - name: '{{ reverse_proxy_net }}'
